### ISSUE TITLE
Check if token price is missing in coingecko results

### ISSUE THREAD

**Issue by yueqiaocertik** [opentvl/opentvl#6]
Currently some tokens may not have price on coingecko. For example the [ACS4 LP](https://bscscan.com/address/0x83D69Ef5c9837E21E2389D47d791714F5771F29b). 

We need to check the result of coingecko, find out the missing tokens and throw an error about that.

**Comment by jtlemkin** [comment]
This commit should show debug logs if we cant use coingecko to get the price for a token: https://github.com/opentvl/opentvl/commit/9be30b44b727d11c042fcec7e50879bc89a506ef.

**Comment by yueqiaocertik** [comment]
Great! 9be30b4 should solve the issue.
